spring:
  datasource:
    url: jdbc:h2:file:./db
    username: pwr
    password: pwr
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dll-auto: update
  h2:
    console:
      enabled: true